packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.9
  "@trpc/client": ^11.0.0-rc.466
  "@trpc/react-query": ^11.0.0-rc.466
  "@trpc/server": ^11.0.0-rc.466
  eslint: ^9.7.0
  prettier: ^3.3.3
  typescript: ^5.5.3
  zod: ^3.23.8
  class-variance-authority: ^0.7.0
  tailwind-merge: ^2.3.0
  clsx: 2.0.0
  dayjs: ^1.11.13

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
